### ISSUE TITLE
Error setting up dev env

### ISSUE THREAD

**Issue by crabsinger** [coordinape/coordinape-backend#51]
From a report: "there are some errors regarding sql when trying to set up the environment"

```
app    | 
app    | In Connection.php line 703:
app    |                                                                                
app    |   SQLSTATE[HY000] [1130] Host '172.22.0.3' is not allowed to connect to this   
app    |   MySQL server (SQL: select * from information_schema.tables where table_sche  
app    |   ma = laravel and table_name = migrations and table_type = 'BASE TABLE')      
app    |                                                                                
app    | 
app    | In Connector.php line 70:
app    |                                                                                
app    |   SQLSTATE[HY000] [1130] Host '172.22.0.3' is not allowed to connect to this   
app    |   MySQL server                                                                 
app    |                                                                                
app    |
```

**Comment by zashton** [comment]
looks like a permission issue arising from connecting from different host

try setting this in your mysql container environment `docker-compose.yml`
`MYSQL_ROOT_HOST: "0.0.0.0"`

**Comment by levity** [comment]
also, what does your `.env` look like? if `DB_HOST=127.0.0.1` i don't think you should run into this issue @Niraj-Kamdar

**Comment by Niraj-Kamdar** [comment]
Still getting the same error.

**Comment by crabsinger** [comment]
@Niraj-Kamdar can you provide some more details on what you've done so far, your dev environment setup, what command you are running that's giving that error, etc. It's quite hard to support debugging this without more information.

**Comment by Niraj-Kamdar** [comment]
I am on Mac M1 and I have followed the same steps described in ReadME except I have to build mysql docker image for ARM arch.
This is the repo from where I build the image: https://github.com/mysql/mysql-docker/tree/main/mysql-server/8.0

**Comment by levity** [comment]
https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8

```
docker pull --platform linux/x86_64 mysql
```
